### ISSUE TITLE
Not able to start the game

### ISSUE THREAD

**Issue by skyshru** [aniketk13/Mini-Project_team-6#1]
Priority:High
Version: c7253b1

User Acceptance Testing: 
The game won't load bcz;

1) There are two .py files inside the src folder
i) Checkers game.py
This name contains space, so while running it on command lines systems, the game won't run causes error

ii) checker_game.py
The application is trying to load an image which does not belong in the directory, which causes an error while initiating the game.

**Comment by aniketk13** [comment]
The game loads from Main.py inside the src folder.

**Comment by aniketk13** [comment]
The game loads from Main.py inside the src folder.
